# Generated by Django 5.0.7 on 2025-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='topic',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CyberTopic',
        ),
    ]
